---
- name: Setup dns server
  hosts: appb
  become: yes

  roles: 
    - role: ifcfg_setup

  tasks:
    - name: Restart NetworkManager
      ansible.builtin.systemd_service:
        name: NetworkManager
        state: reloaded
        enabled: true
  
    - name: Set dns servers in resolv.conf file
      ansible.builtin.include_role:
        name: update_resolv_conf 