---
- name: Modify network configuration using nmcli
  hosts: gateway
  become: yes

  tasks:
    - name: Modify network configuration
      community.general.nmcli:
        state: present
        conn_name: ens35
        type: ethernet
        method4: manual
        ip4: "192.168.10.1/24"
        autoconnect: true
        
    - name: Enable IP forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: 1
        state: present
        reload: yes

    - name: Add NAT rule
      ansible.posix.firewalld:
        zone: public
        masquerade: true
        permanent: true
        state: enabled # Accept connections

    - name: Reload firewall
      ansible.builtin.shell:
        cmd: firewall-cmd --reload

    - name: Restart NetworkManager
      ansible.builtin.systemd_service:
        name: NetworkManager
        state: restarted
        enabled: true