---
- name: Get current network configuration
  hosts: dhcp
  become: true    
  tasks:
    - name: Get current network configuration
      command: ip addr show
      register: network_config_output

    - name: Print network configuration
      debug:
        var: network_config_output.stdout_lines